site_name: curso.dev notes
repo_name: brunononogaki/meubonsai-app-v2
repo_url: https://github.com/brunononogaki/meubonsai-app-v2

nav:
  - Home: index.md
  - Setup do Ambiente:
      - 01. Iniciando o setup do ambiente: 01_setup_ambiente/01_setup_do_ambiente.md
      - 02. Definindo a estrutura de testes: 01_setup_ambiente/02_estrutura_de_testes.md
      - 03. Definindo os Linters: 01_setup_ambiente/03_linters.md
      - 04. Git Overview: 01_setup_ambiente/04_Git_Overview.md
      - 05. Trabalhando com as dependências do projeto: 01_setup_ambiente/05_Dependencias_do_projeto.md
  - Setup do Backend:
      - 01. Criando uma página de status: 02_setup_backend/01_pagina_status.md
      - 02. Integrando um Banco de Dados local: 02_setup_backend/02_banco_local.md
      - 03. Integrando um Banco de Dados de Produção e Staging: 02_setup_backend/03_banco_prod_staging.md
      - 04. Padronizando Erros: 02_setup_backend/04_padronizando_erros.md
      - 05. Padronizando os Controllers: 02_setup_backend/05_padronizando_controllers.md
  - Database Migrations:
      - 01. Configurando o node-pg-migrations: 03_database_migrations/01_Configurando_node-pg-migrations.md
      - 02. Criando os endpoints da API para migrations: 03_database_migrations/02_Criando_API_Migration.md
  - Setup do CI/CD:
      - 01. Estabilizando o ambiente local: 04_setup_cicd/01_Estabilizando_Local.md
      - 02. Criando os testes no CI com GH Actions: 04_setup_cicd/02_Testes_no_CI(GH_Actions).md  
      - 03. Linting de Commits: 04_setup_cicd/03_Linting_de_Commits.md  
  - Setup do Front-End React:
      - 01. Criando a página /status: 05_setup_frontend/01_Criando_pagina_status.md
  - Usuários:
      - 01. Criando a Migration de Users: 06_Usuarios/01_Criando_migration_Users.md
      - 02. Configurando a rota para a criação de Usuários: 06_Usuarios/02_Criacao_de_usuarios.md
      - 03. Definindo as regras de negócio de Users: 06_Usuarios/03_Definindo_Regras_de_Negocio.md
      - 04. Configurando a rota para detalhes de Usuários: 06_Usuarios/04_Detalhes_de_usuarios.md
      - 05. Configurando a rota para updates de Usuários: 06_Usuarios/05_Update_de_usuarios.md
  - Autenticação e Autorização:
      - 01. Implementando a Autenticação: 07_Autenticacao_Autorizacao/01_Implementando_autenticacao.md
      - 02. Criando o endpoint /user: 07_Autenticacao_Autorizacao/02_Endpoint_user.md
      - 03. Implementando o Logout: 07_Autenticacao_Autorizacao/03_Implementando_Logout.md
      - 04. Implementando o MailCatcher e configurando envio de e-mails: 07_Autenticacao_Autorizacao/04_MailCatcher_Envio_emails.md
      - 05. Implementando a Ativação de Conta do Usuário: 07_Autenticacao_Autorizacao/05_Ativacao_do_Usuario.md
      - 06. Implementando o Login do Usuário: 07_Autenticacao_Autorizacao/06_Login_do_Usuario.md
      - 07. Implementando a Autorização: 07_Autenticacao_Autorizacao/07_Implementando_Autorizacao.md
      - 08. Bloqueando endpoints: 07_Autenticacao_Autorizacao/08_Bloqueando_Endpoints.md
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.expand
    - search.highlight
    - search.suggest
    
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
